antinomyhq/forge

.github/workflows/ci.yml, crates/forge_ci/tests/ci.rs
=> Revert "feat: add support for more target architectures and windows os"

README.md
=> chore: replace brackets with `<>`

.github/workflows/ci.yml, crates/forge_ci/tests/ci.rs
=> fix(CI): update build-release job for aarch64 target

.gitignore, crates/forge_app/src/template.rs, crates/forge_app/src/tools/shell/shell_tool.rs, crates/forge_main/src/ui.rs, templates/system-prompt-engineer.hbs, templates/system-prompt-title-generator.hbs
This PR includes several enhancements to improve prompt clarity and tool output formatting:
* Update system prompt template for improved clarity and analysis process
* Enhance performance of data processing in the main module
* Simplify max walker depth setting and update system prompt rules
* Add newline before title format output in shell tool for better readability
* Update JSON file naming convention to include '-dump' suffix
* Restore partial tool information display in title generator template
These changes aim to enhance user experience by improving prompt clarity and output formatting.
=> fix: system prompt improvements and shell tool formatting

crates/forge_tracker/src/log.rs
- **Optimize logging for JSON format in forge_tracker**
- **Integrate logs with PostHog**
=> fix: change logging format to `json`

Cargo.lock, crates/forge_api/Cargo.toml, crates/forge_api/src/executor.rs
=> fix: avoid unwrapping when receiver is dropped.

crates/forge_provider/src/builder.rs, crates/forge_provider/src/open_router/provider.rs
=> fix: parsing error on models response

crates/forge_domain/src/context.rs
fixes https://github.com/antinomyhq/forge/issues/590
=> fix: attachment utf-8 parsing

crates/forge_services/src/template.rs, forge.default.yaml, forge.yaml
Enhance context summarization with standardized templates and configuration
This PR standardizes the context summarization system by implementing a template-based approach across agents and centralizing configuration in the default settings.
These changes improve consistency in how summarization is handled throughout the Forge system and extend summarization capabilities to the software-engineer agent, ensuring a more uniform experience when context summarization is triggered.
The implementation makes three key changes:
1. Updates the default prompt in the template service to use the system-prompt-context-summarizer.hbs template instead of an inline template
2. Moves the compact summarization configuration from forge.yaml to forge.default.yaml and applies it to the software-engineer agent …
=> feat: enhance context summarization with standardized templates and configuration

crates/forge_provider/src/open_router/model.rs
=> feat: make forge LMStudio compatible

crates/forge_display/src/grep.rs, crates/forge_display/src/snapshots/forge_display__grep__tests__combined_grep_suite.snap, crates/forge_display/src/title.rs, crates/forge_services/src/tools/fs/fs_find.rs, crates/forge_services/src/tools/registry.rs, crates/forge_services/src/tools/utils/mod.rs, crates/forge_services/src/tools/utils/path.rs, forge.yaml
=> fix: file-search tool should be used to search for files

crates/forge_api/src/api.rs, crates/forge_api/src/forge_api.rs, crates/forge_domain/src/agent.rs, crates/forge_domain/src/compaction.rs, crates/forge_fs/src/lib.rs, crates/forge_main/src/cli.rs, crates/forge_main/src/ui.rs, crates/forge_services/src/template.rs, templates/system-prompt-context-summarizer.hbs
- **feat: add async read_to_string method for file reading**
- **feat: add upsert_conversation method to API and CLI for conversation management**
=> feat: initialize a conversation from a dump file

README.md, crates/forge_domain/src/orch.rs, crates/forge_domain/src/workflow.rs, crates/forge_main/src/completer/input_completer.rs, templates/system-prompt-engineer-plan.hbs
- **refactor: remove custom rules section and streamline task instructions**
- **feat: add model field to Workflow struct for enhanced agent configuration**
=> feat: setting up default models

crates/forge_main/src/auto_update.rs, crates/forge_main/src/lib.rs, crates/forge_main/src/ui.rs
This PR refactors the auto-update functionality for Forge to improve error handling and ensure updates are properly tracked.
- Changed `update_forge_in_background()` to `update_forge()` that runs asynchronously
- Make the update process wait for completion before exiting the application
- Added proper error message if the update process fails
- Refactored the prompt handling in UI to eliminate duplication
- Fixed state reset in the New command
The code has been tested to ensure that:
- Auto-updates complete properly before app exit
- Error messages are displayed if update fails
- UI functionality works as expected with the refactored prompt handling
These changes improve the reliability of the auto-update process while making the code more maintainable.
=> fix: broken STDIO

crates/forge_main/src/prompt.rs, forge.yaml, templates/system-prompt-engineer-plan.hbs
- **fix: update analysis and action plan structure in system prompt template**
- **fix: add refactoring guidelines for handling failing tests**
- **fix: enhance prompt rendering with current directory and git branch info**
=> feat: shell style prompt improvements

crates/forge_main/src/state.rs, crates/forge_main/src/ui.rs
This PR implements a caching mechanism for model data to improve performance and user experience during model selection. By storing models in the UI state after initial retrieval, we avoid redundant API calls when users interact with model selection functionality.
- Reduces latency and API load by caching model information in the UI state
- Improves responsiveness of the model selection interface by reusing previously retrieved model data
- Maintains data freshness while reducing unnecessary network requests
- Added a new `cached_models` field to `UIState` to store model cache
- Implemented a new `get_models()` method that checks the cache before making API calls
- Updated model selection logic to leverage the cached data
- Ensured proper initialization of the cache in the UI state
=> perf(models): implement model caching to improve selection performance

crates/forge_services/src/compaction.rs
This PR improves the conversation compaction functionality by wrapping compacted summaries in an authoritative context framework. When conversations are compacted to manage token usage, the summaries are now presented with explicit instructions that:
- Mark the summary as authoritative context for reasoning
- Prevent unnecessary reanalysis of previously processed information
- Improve context efficiency in ongoing multi-turn conversations
The enhancement helps AI models maintain conversational coherence while making more efficient use of their context window.
- Added formatting template for compacted summaries in `compaction.rs`
- Implemented clear framing that instructs the model on how to use compacted content
- Improved readability of compacted conversations for debugging purposes
=> fix(compaction): improve context summarization with authoritative framing

templates/system-prompt-engineer-plan.hbs
Improves the structure of implementation plans in the system prompt template for better readability and consistency. Replaces checkbox-style task formatting with numbered sections and standardizes presentation across all plan components.
- Reformats task items to use numbered lists with bold descriptions
- Removes checkbox syntax for more consistent rendering
- Standardizes formatting across tasks, verification criteria, and risks sections
- Maintains all content while improving visual structure
- Clearer visual hierarchy in implementation plans
- More consistent formatting throughout documentation
- Improved readability for both AI and human users
- Better separation between planning sections
=> fix(template): improve implementation plan md format for clarity and consistency

crates/forge_api/src/forge_api.rs, crates/forge_domain/src/api.rs, crates/forge_domain/src/services.rs, crates/forge_main/src/ui.rs, crates/forge_services/src/workflow.rs
=> feat(workflow): implement config file search in parent directories

crates/forge_domain/src/orch.rs
=> fix: zero usage

crates/forge_services/src/tools/fs/fs_find.rs
=> feat: allow search tool to accept file path to search in

crates/forge_domain/src/orch.rs, crates/forge_services/src/tools/fs/fs_write.rs, crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_deep_directory_creation.snap, crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_invalid_rust.snap, crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_single_directory_creation.snap, crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_success.snap, crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_valid_rust.snap, crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_with_different_separators.snap, crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_with_overwrite.snap, forge.default.yaml
This pull request enhances user experience by providing more accurate information in error messages and tool outputs.
- **Enhanced error diagnostics:** Added model information in error messages when models fail to follow instructions, helping users identify which model is struggling and providing clearer guidance on how to proceed
- **Improved file operation feedback:** Fixed path display in FSWrite tool output to show the actual file path rather than a boolean value, making file operation results more readable and understandable
- **Optimized agent performance:** Reduced token threshold for software engineer agent from 120,000 to 80,000, improving performance and responsiveness while maintaining effective context management
=> fix: improve error diagnostics and file operation feedback

crates/forge_infra/src/executor.rs
Fixes: https://github.com/antinomyhq/forge/issues/779
=> fix: quotation issues in windows

crates/forge_domain/src/context.rs, crates/forge_domain/src/conversation_html.rs, crates/forge_domain/src/orch.rs, crates/forge_provider/src/anthropic/provider.rs, crates/forge_provider/src/anthropic/request.rs, crates/forge_provider/src/open_router/request.rs, crates/forge_provider/src/open_router/transformers/drop_tool_call.rs, crates/forge_provider/src/open_router/transformers/set_cache.rs, crates/forge_services/src/compaction.rs
This PR enhances conversation history tracking by storing the model ID with each message in the conversation context. This improvement provides better traceability of which model processed each user message and enables improved rendering in the HTML UI.
- Adds `model` field to `ContentMessage` to track which model was used for each message
- Updates HTML rendering to display model information alongside messages
- Maintains type-safe error handling for model operations
- Optimizes message handling to only store model IDs where needed
- Modified the conversation context to include model ID in message structures
- Updated providers (Anthropic and OpenRouter) to properly handle the model field
- Improved compaction service to correctly preserve model information
- Updated test fixtures to …
=> chore: store model ID with each conversation message

crates/forge_provider/src/builder.rs, crates/forge_provider/src/open_router/provider.rs
=> fix: infinite spinner unstable internet

crates/forge_domain/src/orch.rs, forge.default.yaml
This PR enhances how agents process and respond to completion feedback by implementing two key improvements:
- Optimizes tool call recording by only adding results to collection when completion isn't achieved
- Improves agent reliability by resetting empty tool call counter when instructions are followed
- **fix: reset empty tool call count when instructions are followed**
- **fix: conditionally add tool call results based on completion status**
- **feat: update agent configuration to properly handle task vs feedback inputs**
=> fix: improve agent interaction with completion feedback

crates/forge_main/src/tools_display.rs
Enhances the tool display formatting by adding consistent padding to tool numbers for improved readability and UI alignment. The implementation dynamically calculates the required padding width based on the total number of tools.
- Improves visual clarity by ensuring all tool names start at the same position regardless of the tool count
- Implements dynamic padding calculation based on the maximum number of digits needed
- Simplifies the display format to focus on essential information with proper alignment
- Uses Rust's format specifier with right-alignment and dynamic width
- Calculates maximum digit width based on the total number of tools
- Maintains consistent spacing between numbers and tool names
=> fix(ui): align tool numbering with consistent padding

crates/forge_domain/src/conversation_html.rs
Enhances conversation HTML export functionality by adding a comprehensive All Subscriptions section that displays agent event subscriptions in a structured table format. This improvement provides better visibility into agent subscription patterns and event handling configurations within conversations.
- Added `create_all_subscriptions_section()` function to generate subscription overview table
- Integrated subscription section into main conversation HTML structure
- Implemented functional programming approach using iterators for efficient data processing
- Added proper null checking and empty state handling for conversations without subscriptions
- Created table format showing agent names, subscribed events, and subscription counts
- **File Modified**: …
=> chore(conversation): add All Subscriptions section to HTML rendering

crates/forge_main/src/ui.rs
Enhances user experience by providing clear visual feedback during conversation initialization process. The spinner indicates progress while the system loads existing conversations or creates new ones, preventing the UI from appearing unresponsive.
Addresses the silent initialization phase that could confuse users about whether the system was working properly.
- Added spinner start/stop around conversation initialization logic
- Provided descriptive message "Initializing conversation" to inform users
- Maintained proper error handling and code flow structure
- Improved perceived performance and responsiveness of the CLI
- Better user experience during conversation setup operations  
- No functional changes to the underlying conversation initialization logic
=> fix(ui): add spinner feedback during conversation initialization

crates/forge_domain/src/orch.rs, crates/forge_services/src/tool_service.rs
- **fix(error): improve error formatting for Retryable variant**
- **fix(logging): improve logging format for tool call execution and failure**
=> fix: error message format for tracing

crates/forge_provider/src/error.rs, crates/forge_provider/src/forge_provider/responses.jsonl, crates/forge_provider/src/retry.rs
Significantly improves retry logic with recursive error checking, comprehensive test coverage, and cleaner code structure. The retry mechanism now handles arbitrarily nested transport errors and provides better status code matching logic.
- **Added recursive checking**: New `has_transport_error_code()` function traverses unlimited error nesting depth
- **Enhanced coverage**: Now detects transport errors (ECONNRESET, ETIMEDOUT, ERR_STREAM_PREMATURE_CLOSE) at any nesting level
- **Improved reliability**: Previously only checked 1-2 levels, now handles arbitrarily deep error chains
- **Added missing tests**: Two new test cases for nested and deeply nested transport error scenarios
- **Complete coverage**: Now tests all code paths including recursive error detection
- **Real-world …
=> fix(retry): enhance error detection with recursive checking and comprehensive tests

crates/forge_domain/src/agent.rs, crates/forge_domain/src/context.rs, crates/forge_domain/src/orch.rs, crates/forge_inte/tests/test_workflow.rs, forge.default.yaml
Streamlines agent context management by removing the ephemeral field and simplifying tool initialization logic.
Improves tool handling robustness by better managing empty tool definitions and conditional context overwriting.
Eliminates unused methods and reduces complexity in the agent lifecycle management system.
- **refactor(agent)**: Remove ephemeral field and simplify context initialization logic
- **fix(agent)**: Improve tool context handling by overwriting tools conditionally  
- **refactor(agent)**: Remove unused init_context method and simplify tool handling
- **refactor(context)**: Remove extend_tools method to streamline context management
- **refactor(orchestrator)**: Enhance get_allowed_tools method to handle empty tool definitions
- **fix(tests)**: Remove ephemeral flag from …
=> refactor(agent): simplify context initialization and remove ephemeral field

crates/forge_domain/src/error.rs, crates/forge_domain/src/orch.rs, crates/forge_domain/src/retry_config.rs, crates/forge_infra/src/env.rs, crates/forge_provider/src/client.rs, crates/forge_provider/src/forge_provider/transformers/pipeline.rs, crates/forge_services/src/provider.rs
Consolidates retry logic from provider services into a unified RetryConfig implementation with improved error handling and comprehensive test coverage. Enhances system resilience by implementing exponential backoff strategy with jitter and proper error classification for retryable operations.
- **Centralized retry logic**: Moved retry implementation from ForgeProviderService to RetryConfig domain type for better separation of concerns
- **Enhanced error handling**: Improved error messages and context propagation throughout the retry system
- **Orchestrator improvements**: Converted methods to immutable references and improved usage estimation accuracy
- **RetryConfig domain enhancement**: Added retry() method with exponential backoff strategy using backon crate
- **Environment …
=> refactor(retry): consolidate retry logic and improve error handling system

crates/forge_display/src/grep.rs, crates/forge_main/src/prompt.rs, crates/forge_provider/src/client.rs, crates/forge_services/src/clipper.rs, crates/forge_services/src/tools/fs/fs_remove.rs
Enhances the file removal tool with improved user experience through better path formatting, clearer error messages, and visual feedback integration. The fs_remove tool now provides more intuitive path displays and real-time operation status.
- **Smart Path Display**: Automatically converts absolute paths to relative paths when within the current working directory for cleaner, more readable output
- **Enhanced Error Messages**: File not found and invalid path errors now use the same smart path formatting for consistency
- **Visual Feedback Integration**: Added TitleFormat integration to provide real-time visual feedback during file removal operations
- **Utility Function Extraction**: Created reusable `format_display_path` utility function for consistent path formatting across the …
=> feat(fs): enhance file removal UX with improved path formatting and visual feedback

crates/forge_app/src/input_title.rs, crates/forge_app/src/lib.rs, crates/forge_app/src/tool_registry.rs, crates/forge_display/src/title.rs
Implements a new InputTitle trait for Tools to provide consistent and enhanced formatting of tool execution titles. Refactors ToolRegistry by removing unused context sending functions and enhances TitleFormat with configurable timestamp rendering capabilities.
- **feat: implement InputTitle trait for Tools and enhance TitleFormat rendering**
- Added new `InputTitle` trait with comprehensive tool formatting logic
- Enhanced `TitleFormat` with `render()` method supporting configurable timestamps
- Provides consistent, context-aware titles for all tool types (fs operations, shell commands, network requests)
- **refactor: clean up ToolRegistry by removing unused context sending functions**
- Removed 223 lines of unused context sending functions
- Simplified tool registry implementation by …
=> refactor(ui): implement InputTitle trait and enhance tool formatting display

crates/forge_services/src/provider.rs
Implements efficient model caching in ForgeProviderService to reduce redundant API calls.
Adds cached_models field with mutex-protected cache-first retrieval pattern.
Improves performance by avoiding repeated model list requests for the same provider.
=> feat(provider): implement model caching with cache-first pattern

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/forge_app/src/fmt/fmt_input.rs, crates/forge_app/src/fmt/fmt_output.rs, crates/forge_app/src/operation.rs, crates/forge_ci/src/jobs/build.rs, crates/forge_ci/src/workflow.rs, crates/forge_domain/src/env.rs, crates/forge_infra/Cargo.toml, crates/forge_infra/src/env.rs, crates/forge_infra/src/executor.rs, crates/forge_provider/src/client.rs, crates/forge_services/src/attachment.rs, crates/forge_services/src/provider.rs
This reverts commit https://github.com/antinomyhq/forge/commit/f681745f9884ffd410b800828044fbb67dc0131f.
=> refactor: remove mTLS certificate handling from various components

README.md
fixes: #1151
docs: https://github.com/antinomyhq/antinomyhq.github.io/pull/104
=> doc: update the setting name (max_tool_failure_per_turn)

crates/forge_app/src/fmt/fmt_input.rs, crates/forge_app/src/fmt/fmt_output.rs, crates/forge_app/src/operation.rs, crates/forge_app/src/orch.rs, crates/forge_domain/src/retry_config.rs, crates/forge_infra/src/env.rs, crates/forge_main/src/ui.rs
=> feat: add FORGE_SUPPRESS_RETRY_ERRORS env variable to hide retry error

crates/forge_main/src/info.rs
=> fix: enhance path formatting for display

crates/forge_app/src/orch.rs, crates/forge_domain/src/transformer/mod.rs, crates/forge_domain/src/transformer/reasoning_normalizer.rs, crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_keeps_all_when_first_has_reasoning.snap, crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_removes_all_when_first_assistant_message_has_no_reasoning.snap, crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_when_no_assistant_message_present.snap
reverting this as per discussion on open-router channel
=> Revert "fix: drop reasoning normalizer"

crates/forge_main/src/model.rs, crates/forge_main/src/ui.rs
=> feat: Support for `/retry`

crates/forge_domain/src/tool_name.rs, crates/forge_services/src/mcp/service.rs
fixes https://github.com/antinomyhq/forge/issues/1180
=> fix: mcp `ToolName` sanitization

crates/forge_main/src/ui.rs
Closes https://github.com/antinomyhq/forge/issues/1263
=> fix: sort the models based on the names

crates/forge_main/src/cli.rs, crates/forge_main/src/lib.rs, crates/forge_main/src/main.rs, crates/forge_main/src/sandbox.rs, crates/forge_main/src/ui.rs, forge.yaml
- **feat: add worktree creation support in CLI**
- **fix: update schema reference and add git operations guidelines**
=> feat: forge sandbox

crates/forge_domain/src/context.rs
- **refactor: simplify message rendering using Element for ContextMessage**
- **feat: filter base64 images from ToolOutput in ContextMessage rendering**
=> fix: context limit being exceeded with image URLs

templates/forge-system-prompt-context-summarizer.hbs, templates/forge-system-prompt-engineer-plan.hbs
- **fix: clarify restrictions on plan documentation for AI execution**
- **--wip-- [skip ci]**
=> fix: summarization prompt improvements

crates/forge_domain/src/tool_usage.rs
removes dead code in tests from tool_usage.rs
=> fix: removed dead code

crates/forge_app/src/dto/openai/transformers/tool_choice.rs
=> fix: ensure tool_choice is set only when tools are defined in the req

crates/forge_main/src/ui.rs
=> fix: drop forced login for users

.devcontainer/devcontainer.json, crates/forge_domain/src/agent.rs, crates/forge_main/src/model.rs, crates/forge_main/src/ui.rs, crates/forge_main_neo/src/domain/slash_command.rs, crates/forge_main_neo/src/domain/update_key_event.rs
- **feat: enhance devcontainer configuration with VSCode terminal settings**
- **feat: update devcontainer configuration with additional Git and GitHub CLI features**
- **feat: add Sage command and update agent handling in spotlight navigation**
=> feat: add `/sage` command

crates/forge_app/src/compact.rs, crates/forge_domain/src/compaction_strategy.rs, templates/forge-partial-summary-frame.md, templates/forge-system-prompt-context-summarizer.md
- **fix: update compaction logic to prioritize assistant messages**
- **fix: include user feedback in compaction summary generation**
=> fix: improve compaction focus

crates/forge_app/src/orch.rs, crates/forge_app/src/orch_spec/orch_setup.rs, crates/forge_services/src/agent_loader.rs
fixes https://github.com/antinomyhq/forge/issues/1539
=> fix: show attempt-completion in `/tools` for all agents

crates/forge_main/src/model.rs, crates/forge_main/src/ui.rs, plans/2025-09-13-dynamic-agent-slash-commands-v3.md
fixes https://github.com/antinomyhq/forge/issues/1533
=> feat: insert `/agent-<agent-name>` aliases

README.md, crates/forge_app/src/fmt/fmt_output.rs, crates/forge_app/src/operation.rs, crates/forge_app/src/orch_spec/orch_setup.rs, crates/forge_domain/src/env.rs, crates/forge_infra/src/env.rs, crates/forge_infra/src/executor.rs, crates/forge_main/src/info.rs, crates/forge_services/src/attachment.rs, crates/forge_services/src/tool_services/shell.rs, plans/2025-09-13-forge-history-file-env-var-v2.md
fixes https://github.com/antinomyhq/forge/issues/1521
=> feat: add `FORGE_HISTORY_FILE` env variable

crates/forge_app/src/orch.rs, crates/forge_app/src/orch_spec/orch_spec.rs, crates/forge_domain/src/chat_response.rs, crates/forge_domain/src/tool_call.rs, crates/forge_main/src/ui.rs
- **fix: update tool completion tracking and add test for consecutive tool calls**
- **fix: enhance interruption reason with error tracking and update UI formatting**
=> fix: unexpected tool call failure limits being hit

crates/forge_main/src/cli.rs, crates/forge_main/src/completer/command.rs, crates/forge_main/src/main.rs, crates/forge_main/src/model.rs, crates/forge_main/src/ui.rs, shell-plugin/forge.plugin.zsh
=> chore: improve ZSH compatibility

shell-plugin/forge.plugin.zsh
- **fix(zsh): improve buffer parsing and user action handling in forge plugin**
- **feat: add history**
=> fix: many fixes

crates/forge_main/src/ui.rs
=> fix: raise an error if no provider is configured.

crates/forge_main/src/banner.rs, crates/forge_main/src/cli.rs, crates/forge_main/src/cli_format.rs, crates/forge_main/src/lib.rs, crates/forge_main/src/main.rs, crates/forge_main/src/ui.rs, shell-plugin/README.md, shell-plugin/forge.plugin.zsh
=> feat: add session management commands for handling conversations

crates/forge_app/src/dto/app_config.rs, crates/forge_services/src/provider/registry.rs, shell-plugin/forge.plugin.zsh
=> feat: persist provider specific model

crates/forge_api/src/forge_api.rs, crates/forge_app/src/dto/app_config.rs, crates/forge_app/src/dto/provider.rs, crates/forge_infra/src/database/repository/app_config.rs, crates/forge_infra/src/env.rs, crates/forge_services/src/provider/models.json, crates/forge_services/src/provider/registry.rs
- **feat: refactor provider handling and add provider configuration from JSON**
- **fix: standardize provider IDs to lowercase in models.json and update enum serialization**
=> refactor: move model configuration into a JSON file

Cargo.lock, crates/forge_main/Cargo.toml, crates/forge_main/src/cli.rs, crates/forge_main/src/env.rs, crates/forge_main/src/model.rs, crates/forge_main/src/ui.rs, shell-plugin/forge.plugin.zsh
=> feat: add 'show-tools' command and update zsh plugin

crates/forge_app/src/dto/provider.rs, crates/forge_services/src/provider/provider.json
=> feat: add BigModel provider

crates/forge_main/src/ui.rs
=> fix: agent ID retrieval in tools command
