antinomyhq/forge

- install.sh
Since MUSL is generally used in embedded systems, we should by default use GNU.
> feat: set default to gnu instead of throwing an error

- crates/forge_app/src/tools/fs/fs_write.rs
This PR adds an optional  flag to the  struct used by the file system write tool. When  is set to  (the default) and the file exists, the tool will now return an error with the existing file content rather than silently overwriting the file.
- Added an optional  boolean field to  with a default value of 
- Updated the file writing logic to check if the file exists and whether the overwrite flag is set
- Added comprehensive test cases for both overwrite enabled and disabled scenarios
- All existing tests continue to pass with the new functionality
This improves safety by preventing accidental file overwrites while providing clear feedback to users. The error message includes the content of the existing file and instructions on how to enable overwriting if needed.
All tests pass, including …
> feat: add overwrite option to FSWriteInput for file writing behavior

- README.md
- crates/forge_domain/src/agent.rs
- crates/forge_domain/src/orch.rs
This PR makes the system_prompt and user_prompt fields optional for agents.
- Modified the Agent struct to make system_prompt and user_prompt optional fields
- Updated the orchestrator to handle cases when these fields are not provided
- Updated documentation in README.md to reflect the optional nature of these fields
When system_prompt is not provided, no system message will be added to the context.
When user_prompt is not provided, the raw event value will be used as input.
The documentation now indicates these fields are optional but recommends providing system_prompt for best results.
> refactor: Make system_prompt and user_prompt fields optional for agents

- .config/nextest.toml
This PR adds a nextest.toml configuration file in the .config directory to set default test timeouts. Tests will be marked as SLOW after 1 second and will be terminated after 30 seconds.
> chore: add nextest.toml configuration for test timeouts

- .ignore
- crates/forge_app/src/template.rs
- crates/forge_domain/src/agent.rs
- Change `walker_depth` field to `max_walker_depth` (Option<usize>)
- Remove default walker depth method
- Only set max depth when explicitly provided
- Add .ignore file for auto-complete snapshots
> fix: Make walker depth optional and more flexible in template agent

- crates/forge_app/src/tools/patch/apply_json.rs
This PR enhances the `ApplyPatchJson` tool to display diff output when patches are applied, similar to what's already implemented in `apply.rs`. It also refactors the code by inlining the `process_file_modifications` function for cleaner and more direct implementation.
- Added import for `DiffFormat` from `forge_display` crate
- Added code to capture the original file content before modification
- Added functionality to display the diff between old and new file content
- Inlined the `process_file_modifications` function directly into the `call` method
- Removed the now-redundant helper function
This change brings consistency between the two patch application implementations (`apply.rs` and `apply_json.rs`). Users will now see a helpful diff output when using the JSON patching tool, making …
> fix: add diff output display to `apply_json.rs`

- crates/forge_app/src/tools/fs/fs_write.rs
- crates/forge_app/src/tools/patch/apply.rs
- crates/forge_app/src/tools/patch/apply_json.rs
- crates/forge_display/src/diff.rs
This PR enhances the patching functionality to allow multiple patch operations in a single call.
- Added a new Input struct with a patches field to handle multiple patch operations
- Implemented sequential application of patches with individual diff generation for each step
- Modified DiffFormat to include operation type (patch/create/overwrite) in the diff title
- Added better string conversion for Operation enum using AsRefStr
All unit tests for the patch functionality are passing. The only failing tests are the API integration tests which are failing due to a tracing initialization issue unrelated to the patch functionality changes.
- Allows for more complex file modifications in a single API call
- Provides clearer diff output with operation-specific titles
- Reduces the number of …
> feat(patch): support multiple-patch operations in a single call

- crates/forge_api/src/executor.rs
- crates/forge_domain/src/agent.rs
- crates/forge_domain/src/chat_request.rs
- crates/forge_domain/src/event.rs
- crates/forge_domain/src/orch.rs
- crates/forge_inte/tests/api_spec.rs
- crates/forge_main/src/ui.rs
This PR refactors the communication model in forge to use explicit events instead of raw content strings. The change makes the event flow more explicit across the system and simplifies the codebase.
- Replace ChatRequest.content with Event object
- Simplify ForgeExecutor by removing environment and tool services
- Move event type constants from domain layer to UI layer
- Update Orchestrator to use direct event dispatch
- Add input field to Transform::User for bidirectional communication
- Update tests and integration to use new event-based API
Most tests pass, though there are some integration test failures related to tracing initialization which should be addressed separately. These failures are not directly caused by the code changes in this PR.
This refactoring is part of a larger …
> refactor: migrate from content-based to event-based communication model

- crates/forge_api/src/loader.rs
- forge.default.yaml
- Move default configuration to forge.default.yaml 
- Update loader to reference forge.default.yaml instead of forge.yaml
- Add max_walker_depth parameter to software-engineer agent
This PR separates the default config from the user config, making it easier to manage user-specific configuration without affecting the embedded default configuration.
> fix: separate default forge config from user config

- README.md
This PR adds a new section about application logs to the README.md file. It includes:
- New section about viewing application logs with clear examples
- Information on locating log files using the /info command
- Instructions for using jq to format JSON logs for better readability
- Demo GIF moved to the top of README for better visibility
- Improved organization of log-related documentation
These changes improve the documentation by providing clear instructions for users on how to access and analyze application logs, which is important for troubleshooting and understanding the application's behavior.
> doc: add application logs documentation to README

- README.md
- crates/forge_domain/src/context.rs
- crates/forge_domain/src/provider.rs
- crates/forge_infra/src/env.rs
This PR adds support for configuring custom provider URLs for OpenAI-compatible API providers including Open Router.
- Add 'open_ai_url' method to the Provider enum to allow setting custom URLs
- Refactor provider key functions to accept string slices for better memory efficiency
- Check for 'OPENAI_URL' environment variable to configure custom endpoints
- Update README with comprehensive documentation on provider configuration options
- Add examples of custom URLs configuration for different scenarios
- Addresses the need for connecting to self-hosted or enterprise OpenAI-compatible models
- Improves flexibility for users with custom API endpoints
- Supports proxy services and regional API deployments
- Tested with default Open Router endpoint
- Tested with custom URL configuration
- …
> feat(provider): add support for custom provider URLs

- README.md
- crates/forge_app/src/provider.rs
- crates/forge_app/src/template.rs
- crates/forge_domain/src/agent.rs
- crates/forge_domain/src/lib.rs
- crates/forge_domain/src/orch.rs
- crates/forge_inte/tests/test_workflow.yaml
- crates/forge_open_router/src/anthropic/provider.rs
- crates/forge_open_router/src/builder.rs
- crates/forge_open_router/src/open_router/api.rs
- forge.default.yaml
- forge.yaml
This PR changes how tool support is configured in the application by moving it from the provider level to the agent configuration level.
1. Added a new 'tool_supported' Boolean field to the Agent struct to explicitly control whether tools are available to the LLM
2. Modified the system context to use this flag directly instead of querying provider parameters
3. Updated the README documentation with details about the new configuration option
4. Removed the deprecated parameters() method from ProviderService and its implementations
- Simplified architecture by removing a provider-level API call
- Improved control over tool behavior at the agent configuration level
- Added the ability to force XML-based tool calls even for models that natively support tools
All tests pass with the new …
> feat(tools): introduce agent-level tool support configuration

- crates/forge_app/src/template.rs
- crates/forge_domain/src/agent.rs
- crates/forge_main/src/model.rs
- crates/forge_main/src/state.rs
- crates/forge_main/src/ui.rs
- forge.default.yaml
- forge.yaml
- templates/system-prompt-help.hbs
This PR implements a dedicated help command mode for the Forge CLI application that allows users to get assistance and documentation directly from the CLI.
- Added a new '/help' command to switch to help mode
- Created a help agent with a specialized system prompt template
- Integrated README content into templates to provide documentation context
- Added event handling for user help queries
- Updated the agent model to use google/gemini-2.0-flash-thinking-exp for better response quality
- Enhanced the UI to display mode-specific messages
- Added new SystemContext.readme field to include README content in prompts
- Created a system-prompt-help.hbs template with specific instructions for help responses
- Updated the state handling to include the new HELP mode
- Configured the help_agent in …
> feat: add help command mode with dedicated help agent

- crates/forge_open_router/src/open_router/transformers/drop_or_fields.rs
- crates/forge_open_router/src/open_router/transformers/mod.rs
- crates/forge_open_router/src/open_router/transformers/pipeline.rs
- crates/forge_tracker/src/dispatch.rs
This PR improves the OpenRouter integration with two key changes:
1. Renamed `OpenAITransformer` to `DropOpenRouterFields` to better reflect its purpose
2. Updated the pipeline transformation to use the renamed component consistently
3. Removed redundant debug logging in the event dispatch system
- feat: add open router dropper (8458ac57)
- fix(tracker): remove redundant debug logging in event dispatch (9c93b34b)
- fix(open_router): replace OpenAITransformer with DropOpenRouterFields in pipeline transformation (85dbf4ff)
All existing tests continue to pass.
> fix(open_router): replace OpenAITransformer with DropOpenRouterFields and remove redundant logging

- templates/system-prompt-engineer.hbs
This PR updates the system-prompt-engineer.hbs template to require creating a structured Markdown file as the final artifact in PLAN mode. The file must include:
1. **Objective**: A clear statement of the high-level goal and purpose
2. **Implementation Plan**: Detailed steps on how to proceed with implementation  
3. **Verification Criteria**: Specific conditions to verify that the work is completed successfully
The naming convention for these files is established as `plan-{task-name}.md` (e.g., `plan-api-refactoring.md`).
> fix: add Markdown file requirements for PLAN mode

- crates/forge_main/src/state.rs
- crates/forge_main/src/ui.rs
This PR improves the way we track whether a message is the first one in a conversation by:
1. Adding an `is_first` boolean flag to the `UIState` struct
2. Creating a custom `Default` implementation for `UIState` where `is_first` is initialized to `true`
3. Replacing the complex conversation history check with this simple boolean flag
The previous approach required querying the conversation history to determine if a message was the first one, which was more complex and potentially less reliable. This change simplifies the logic and makes it more deterministic.
- Added `is_first: bool` field to `UIState` struct
- Implemented custom `Default` for `UIState` 
- Updated the `chat` method to use this flag instead of querying conversation history
> fix: simplify title generation event logic

- crates/forge_main/src/prompt.rs
- crates/forge_main/src/state.rs
- crates/forge_main/src/ui.rs
Fixes failing tests in the `prompt.rs` file by updating the test expectations to match the actual implementation. The tests were failing because they expected the VERSION constant to be displayed without a "v" prefix in the prompt, but the actual implementation includes this prefix.
- Updated `test_render_prompt_right_with_usage` test to correctly handle the VERSION format in expectations
- Updated `test_render_prompt_right_without_usage` test to correctly handle the VERSION format in expectations
All tests are now passing:
```
test result: ok. 21 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
The issue was in the format string used in the test expectations. The tests were expecting:
```
[ACT/v{VERSION}/30]
```
But needed to be:
```
[ACT/{VERSION}/30]
```
since the actual …
> fix(prompt): version format in prompt

- crates/forge_inte/tests/test_workflow.rs
- forge.default.yaml
- templates/partial-system-info.hbs
- templates/system-prompt-advocate.hbs
- templates/system-prompt-engineer.hbs
- templates/system-prompt-git-commit.hbs
- templates/system-prompt-github-engineer.hbs
- templates/system-prompt-github-pull-request.hbs
- templates/system-prompt-help.hbs
This PR introduces a reusable system information template component and adds GitHub CLI integration capabilities to the pull request creation workflow.
These changes improve maintainability by centralizing system information display logic across templates and enhance functionality by enabling automated PR submission directly from the Forge CLI.
1. Extracted repetitive system information sections into a reusable `partial-system-info.hbs` template
2. Updated all system prompt templates to use this new partial
3. Enhanced the GitHub PR template with step-by-step instructions for PR submission using GitHub CLI
4. Updated test workflow to use the new partial template
5. Adjusted relevant configuration in forge.default.yaml
The changes were tested by verifying template rendering in the updated …
> fix(templates): enhance PR template with GitHub CLI integration and system info partials

- .github/workflows/ci.yml
- crates/forge_ci/tests/ci.rs
This PR adds an npm package publishing step to the CI workflow, similar to the existing Homebrew release step.
- Added npm_release job to CI workflow in forge_ci/tests/ci.rs
- The job runs after the semantic release
- Uses same dependencies and conditions as the homebrew_release job
- Checks out npm-code-forge repository and runs update-package.sh script
- Resolves #528
- NPM_ACCESS - GitHub token with repository access permissions
- NPM_TOKEN - NPM authentication token for package publishing
This implementation assumes a separate npm-code-forge repository will be created as described in issue #528.
NPM packacge repo link https://github.com/antinomyhq/npm-code-forge
> feat: add npm package publishing to CI workflow

- .github/workflows/forge-automation.yml
- crates/forge_ci/tests/forge_automation.rs
This PR fixes the issue with JSON parsing errors when comments contain special characters like carriage returns and newlines.
- Modified the workflow to use GitHub Actions' built-in toJSON() function to properly escape comment bodies
- Improved the forge_event_json function to properly handle escape sequences
- Added a unit test to verify special characters are properly escaped
Fixes the CI error in PR #545 where control characters in comments were breaking JSON parsing.
> chore(ci): JSON parsing error with special characters in comments

- crates/forge_domain/src/chat_response.rs
- crates/forge_domain/src/orch.rs
- crates/forge_main/src/ui.rs
> fix: Update message sending logic to include Custom type responses

- crates/forge_api/src/api.rs
- crates/forge_api/src/executor.rs
- crates/forge_app/src/conversation.rs
- crates/forge_domain/src/conversation.rs
- crates/forge_domain/src/lib.rs
- crates/forge_domain/src/orch.rs
This PR refactors the conversation state management system to fix an issue where agent states incorrectly remain marked as active after Ctrl+C interruptions, leading to potential state corruption in subsequent interactions.
When users interrupt a conversation with Ctrl+C, the `is_active` flags on agents remained set to `true`, causing incorrect behavior if the conversation was resumed later. This refactoring removes the problematic flag entirely and fundamentally redesigns how agent activity is tracked and synchronized.
The implementation takes a three-pronged approach:
1. **Architecture Change**: The `Orchestrator` now maintains the conversation in memory with proper synchronization using `RwLock`, rather than repeatedly fetching it from storage.
2. **State Management**: Removed the …
> fix(#561): Redesign conversation state management to address agent persistence after interruptions

- crates/forge_domain/src/provider.rs
Fixes: https://github.com/antinomyhq/forge/issues/599
> fix: ensure URLs end with a trailing slash in Provider methods

- crates/forge_services/src/tools/shell/executor.rs
> fix: preserve coloured output for sbt tests

- crates/forge_services/src/tools/shell/shell_tool.rs
**BEFORE**
**AFTER**
fixes #602
> refactor: simplify command output formatting in shell execution

- crates/forge_domain/src/agent.rs
- crates/forge_domain/src/orch.rs
- crates/forge_domain/src/services.rs
- crates/forge_services/src/compaction.rs
- crates/forge_services/src/conversation.rs
This PR moves the compaction decision logic from the compaction service to the orchestrator, improving separation of concerns. The orchestrator now determines when compaction should occur while the compaction service focuses solely on applying the compaction.
- **Better Separation of Concerns:** Orchestrator makes decisions, services perform actions
- **Simplified API:** CompactionService now has a cleaner interface focused only on its core responsibility
- **Improved Code Organization:** Added a helper method to Agent for determining if compaction is needed
- **Guaranteed Compaction Command:** Ensures the /compact command will always compress the context regardless of thresholds
1. Added 'should_compact' method to the Agent struct that reuses the existing logic from Compact
2. Simplified …
> fix(compaction): move decision logic to orchestrator for better separation of concerns

- Cargo.lock
- crates/forge_main/Cargo.toml
- crates/forge_main/src/lib.rs
- crates/forge_main/src/model.rs
- crates/forge_main/src/tools_display.rs
- crates/forge_main/src/ui.rs
Adds a dedicated formatter for  command output and refactors tool display logic out of the Info struct. Provides a clearer and more structured listing of available tools within the Forge CLI.\n\n- Implements a new  function in a dedicated module () for consistent tool information display.\n- Formats tool name as blue and bold, description with default styling, and input JSON schema as dimmed multi-line text.\n- Removes redundant tool formatting logic from the  struct to centralize display concerns.\n- Updates the  command handler in the UI to utilize the new formatting function.
> feat(cli): enhance  command output and refactor formatting

- Cargo.lock
- crates/forge_domain/src/conversation_html.rs
- crates/forge_domain/src/tool_call_parser.rs
- crates/forge_infra/src/executor.rs
- crates/forge_provider/src/open_router/provider.rs
- crates/forge_provider/src/open_router/request.rs
- crates/forge_provider/src/open_router/transformers/set_cache.rs
- crates/forge_provider/src/open_router/transformers/transformer.rs
- crates/forge_services/Cargo.toml
- crates/forge_services/src/tools/fs/fs_undo.rs
- crates/forge_services/src/tools/patch.rs
- forge.yaml
- templates/partial-system-info.hbs
- templates/partial-tool-information.hbs
Enhances the patch tool to return a plain text diff as the final output instead of XML content. The implementation maintains colored diffs for the interactive display while ensuring that the final output uses text-only formatting without ANSI color codes.
- Added `format_plain` and `format_with_options` methods to `DiffFormat` in forge_display
- Modified the `format_output` function in patch.rs to return plain text diffs
- Maintained backward compatibility with tests
- Added a new test to verify plain text output has no ANSI codes
All tests pass with the new implementation. Added a specific test for the plain text output.
> feat(display): add plain text diff output to patch tool

- crates/forge_services/src/template.rs
The ForgeTemplateService contains a Handlebars instance that could potentially be accessed from multiple threads, causing thread safety issues during concurrent template rendering operations.
- The Handlebars instance was not wrapped in a thread-safe container
- This could lead to race conditions and unexpected behavior in concurrent scenarios
- The method call needed to be updated for consistency
Wrapped the Handlebars instance in an Arc (Atomic Reference Counter) to ensure thread safety when the template service is used across multiple threads.
- Improves concurrency handling for template operations
- Prevents potential race conditions during template rendering
- Makes the service more robust for parallel processing scenarios
- Better aligns with Rust's thread safety guarantees
> fix(template): template rendering error

- crates/forge_display/src/markdown.rs
- crates/forge_domain/src/orch.rs
This PR enhances the robustness of the tool execution system by implementing intelligent truncation of interrupted tool responses. It prevents execution of malformed or partial tool instructions by precisely locating and preserving only complete tool calls.
This PR enhances the reliability of the tool response handling mechanism in the Orchestrator by properly truncating incomplete tool calls.
- Improves how we handle interrupted tool responses by finding the last valid tool call and truncating properly
- Uses pattern matching to locate the closing tag of the last complete tool call
- Properly truncates any partial/incomplete tool calls after the interruption point
- Helps prevent potential parsing errors or execution of incomplete tool instructions
The change uses `rmatch_indices` to …
> fix(orchestrator): improve handling of interrupted tool responses

- forge.default.yaml
This PR adds explicit instructions to the software-designer agent to only create and update plans, and not modify any code files. This prevents the agent from making unwanted code changes when it should be focused on planning.
These restrictions help maintain a clear separation of concerns between the planning and implementation phases in the software development workflow.
> fix(software-designer): restrict agent to plan creation only

- crates/forge_domain/src/agent.rs
- crates/forge_domain/src/message.rs
- crates/forge_domain/src/orch.rs
- crates/forge_main/src/info.rs
- crates/forge_main/src/prompt.rs
- crates/forge_main/src/state.rs
- crates/forge_main/src/ui.rs
- crates/forge_provider/src/anthropic/response.rs
- crates/forge_provider/src/open_router/response.rs
- Added `estimated_tokens` field to track estimated token counts
- Enhanced orchestrator to calculate estimates from context
- Updated UI to display both reported and estimated totals
- Added provider support for Anthropic and OpenRouter
No breaking changes - `estimated_tokens` is optional and defaults to `None`.
/claim #713
> feat: add token estimation feature

- crates/forge_display/src/diff.rs
- crates/forge_display/src/markdown.rs
- crates/forge_display/src/title.rs
- crates/forge_domain/src/orch.rs
- crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_failed_call.snap
- crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_successful_call.snap
- crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_with_special_chars.snap
- crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage_prompt_to_string.snap
- crates/forge_domain/src/tool_call.rs
- crates/forge_domain/src/tool_call_context.rs
- crates/forge_domain/src/tool_call_record.rs
- crates/forge_domain/src/tool_usage.rs
- crates/forge_main/src/input.rs
- crates/forge_main/src/ui.rs
- crates/forge_services/src/tools/fetch.rs
- crates/forge_services/src/tools/fs/file_info.rs
- crates/forge_services/src/tools/fs/fs_find.rs
- crates/forge_services/src/tools/fs/fs_read.rs
- crates/forge_services/src/tools/fs/fs_undo.rs
- crates/forge_services/src/tools/registry.rs
- crates/forge_services/src/tools/shell.rs
- crates/forge_spinner/src/lib.rs
- forge.default.yaml
- forge.yaml
- templates/partial-tool-information.hbs
- templates/partial-tool-required.hbs
- templates/partial-tool-use-example.hbs
This PR enhances the tool call handling and fixes critical compilation errors affecting the FSFileInfo tool and UI components. The primary improvements include:
- Properly implements the FSFileInfo tool with Infrastructure parameter support to fix compilation errors
- Addresses type conversion issues in UI spinner component by converting TitleFormat to String
- Improves tool usage instructions with better JSON schema-based formatting
- Enhances display consistency across tool invocations with standardized formatting
- Refactors FSFileInfo to properly handle Arc<F> infrastructure parameter
- Updates all test cases to conform to the new interface
- Adds proper type conversion for TitleFormat in UI components
- Improves text handling in various display modules
- Simplifies tool usage …
> fix(tools): use JsonSchema instead of XML to Parse Tools

- templates/partial-tool-information.hbs
> fix: never reveal tool name to user

- Cargo.lock
- crates/forge_main/src/ui.rs
- crates/forge_spinner/Cargo.toml
- crates/forge_spinner/src/lib.rs
This PR fixes issue #769: Spinner '/compact' is stuck at 0 seconds.
When running the '/compact' command, the spinner shows a timer that should be updated every second, but it stays at 0 seconds throughout the operation.
- Created a dedicated tokio task in the SpinnerManager to track and update the elapsed time every 500ms
- Modified the spinner management to properly handle updates during long-running operations
- Added proper handling of CTRL+C interruptions during compaction operations
- Ensured the tracker task is properly dropped when stopping the spinner
- Refactored the compaction handling in UI to gracefully handle both successful completions and interruptions
- The spinner now shows the correct elapsed time during compaction operations
- Users can interrupt the compaction process …
> fix: compaction spinner updates and interruption

- crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage_prompt_to_string.snap
- crates/forge_domain/src/tool_usage.rs
This PR enhances the tool usage schema by adding tool descriptions and improving the output format.
- Adds tool description field to the Schema struct to expose tool descriptions in the LLM prompt
- Wraps tool schema JSON in <tool> tags for better parsing and readability
- Updates the corresponding snapshot tests to reflect these changes
These changes improve the information available to LLM models about each tool, leading to better tool selection and usage.
> fix: include tool description in schema

- crates/forge_display/src/markdown.rs
- crates/forge_domain/src/conversation.rs
This PR addresses an issue with model configuration inheritance in workflows. Previously, when a workflow specified a model, it would update agent models but not properly initialize compaction configurations for agents that didn't have them already. This fix ensures all agents receive consistent model configurations for both regular operation and compaction.
- **fix(domain)**: Ensure workflow models are applied to agent compact configurations
- Added initialization of Compact objects for agents when only a workflow model is provided
- Updated existing compact models to use the workflow model when specified
- Added tests to verify proper inheritance behavior
- **fix(display)**: Simplify codeblock style initialization in MarkdownFormat
- Removed unnecessary mutable style object and …
> fix(domain): ensure workflow model updates agent compaction configurations

- crates/forge_domain/src/agent.rs
- crates/forge_domain/src/context.rs
- crates/forge_domain/src/conversation.rs
- crates/forge_main/src/ui.rs
Fixes serde deserialization errors that occurred when loading previously saved conversations by adding missing `#[serde(default)]` attributes to optional fields across domain structures. This ensures backward compatibility when loading conversations that may be missing certain fields in their serialized format.
- **Agent struct**: Added `#[serde(default)]` to all optional fields (model, description, system_prompt, user_prompt, ephemeral, tools, subscribe, max_turns, max_walker_depth, compact, custom_rules)
- **Context struct**: Added `#[serde(default)]` to optional collection and configuration fields (messages, tools, tool_choice, max_tokens, temperature)
- **AgentState struct**: Added `#[serde(default)]` to optional context field
- **Deserialization errors**: Fixed crashes when loading …
> fix(domain): resolve serde deserialization errors for conversation loading

- crates/forge_display/src/diff.rs
- crates/forge_inte/tests/api_spec.rs
- crates/forge_main/src/input.rs
- crates/forge_main/src/ui.rs
- crates/forge_provider/src/forge_provider/provider.rs
- crates/forge_services/src/tools/fs/fs_read.rs
- crates/forge_services/src/tools/registry.rs
This PR standardizes the application's error handling by replacing println with eprintln for error messages and logging information. This ensures all diagnostic output is properly directed to stderr, improving application output and log management.
- Streamlines console output by directing errors to stderr consistently
- Removes unnecessary debug output (particularly in fs_read tests)
- Simplifies error formatting in forge_provider module
These changes make the application's logging more consistent and follow Rust best practices for console output management.
> fix: standardize error output using eprintln instead of println

- crates/forge_domain/src/orch.rs
- crates/forge_domain/src/services.rs
- crates/forge_domain/src/tool_call_context.rs
- crates/forge_domain/src/tool_name.rs
- crates/forge_domain/src/tool_result.rs
- crates/forge_main/src/ui.rs
- crates/forge_services/src/tool_service.rs
- forge.default.yaml
- forge.yaml
Improves error handling for unsupported tool calls by returning a descriptive ToolResult to the agent instead of throwing an exception.
When an agent tries to use an unsupported tool, it now gets a helpful error message with a list of available tools rather than failing with an exception. This enhances the agent's ability to recover and retry with appropriate tools.
Fixes #842
> fix(tools): return error to agent instead of raising exception

- crates/forge_main/src/cli.rs
- crates/forge_main/src/ui.rs
Change the type of name and command_or_url fields from Option<String> to String in McpAddArgs struct, removing unnecessary unwrap_or_default() calls and context checks in the UI implementation.
> fix: make name and command_or_url required in McpAddArgs

- crates/forge_main/src/completer/search_term.rs
- crates/forge_main/src/completer/snapshots/forge_main__completer__search_term__tests__marker_based_search_chinese.snap
- crates/forge_main/src/completer/snapshots/forge_main__completer__search_term__tests__marker_based_search_chinese_with_spaces.snap
- crates/forge_main/src/completer/snapshots/forge_main__completer__search_term__tests__marker_based_search_emoji.snap
- crates/forge_main/src/completer/snapshots/forge_main__completer__search_term__tests__marker_based_search_mixed_chinese_english.snap
The `SearchTerm::process()` method panics when processing input containing multi-byte UTF-8 characters (e.g., Chinese characters) due to incorrect string slicing at non-character boundaries.
**Error example:**
- Properly use `char_indices()` for all string indexing operations
- Ensure string slicing only occurs at valid character boundaries
- Maintain correct mapping between character positions and byte indices
fixes #888 
This fix ensures the search term completer works correctly with international characters.
> fix: handle UTF-8 character boundaries in SearchTerm processing (#888)

- crates/forge_app/src/execution_result.rs
- crates/forge_app/src/orch.rs
- crates/forge_app/src/tool_registry.rs
- crates/forge_app/src/utils.rs
- crates/forge_services/src/attachment.rs
- forge.yaml
- **refactor: simplify return types in tool output functions and update display_path function**
- **refactor: update attachment handling to avoid truncation and simplify content generation**
> fix: use XML based format for attachments

- crates/forge_domain/src/compaction_strategy.rs
- crates/forge_domain/src/context.rs
This pull request enhances the context compaction strategy to correctly handle scenarios with parallel tool calls. The core improvement is in the  function, which now intelligently adjusts the compaction sequence to prevent truncation of tool results when multiple tool calls occur in parallel.
Core functionality improvements:
- **Improved Compaction Strategy:** The compaction logic now correctly identifies and preserves sequences of tool results, ensuring that no tool call information is lost during context summarization.
- **Robustness:** New tests have been added to validate the handling of various parallel tool call patterns, making the compaction process more reliable.
- **New  method:** A new helper method  has been added to  to simplify checking for tool results.
> fix(compaction): handle parallel tool calls in context compaction

- Cargo.lock
- crates/forge_infra/Cargo.toml
- crates/forge_infra/src/forge_infra.rs
- crates/forge_infra/src/lib.rs
- crates/forge_infra/src/walker.rs
- crates/forge_services/src/discovery.rs
- crates/forge_services/src/forge_services.rs
- crates/forge_services/src/infra.rs
- crates/forge_services/src/tool_services/fs_search.rs
This refactoring migrates the filesystem walker functionality from forge_services to forge_infra, introducing new infrastructure abstractions that improve separation of concerns and enable better dependency injection patterns. The changes establish a cleaner architecture where infrastructure concerns are properly isolated from service logic.
- **Moved walker implementation** from forge_services to forge_infra as 
- **Added WalkerInfra trait** in forge_services/infra.rs for dependency injection
- **Created WalkerConfig** with conservative and unlimited preset configurations
- **Updated ForgeFsSearch** to use WalkerInfra dependency injection instead of direct forge_walker usage
- **Enhanced file discovery service** to use the new walker infrastructure
- **Improved async file operations** by …
> refactor: migrate walker functionality to forge_infra with new abstractions

- crates/forge_infra/src/env.rs
- crates/forge_main/src/main.rs
I've noticed that when using the forge tool, if the API key is not set via environment variables, the program directly panics.
```
thread 'main' panicked at crates/forge_infra/src/env.rs:72:32:
No API key found. Please set one of: FORGE_KEY, OPENROUTER_API_KEY, OPENAI_API_KEY, ANTHROPIC_API_KEY
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I understand that this is intended to prompt the user to configure the necessary API key. However, I believe that causing the program to crash outright (panic) is not the ideal way to handle this situation.
The absence of an API key is typically an **oversight** in user configuration rather than a fundamental **program error**. A more appropriate approach would be to print a clear notification or warning message, …
> fix: replace panic with proper error handling in API key resolution

- crates/forge_provider/src/forge_provider/request.rs
- crates/forge_provider/src/forge_provider/transformers/make_openai_compat.rs
> fix: use `max_completion_tokens` instead of `max_tokens` for open-ai compatible providers

- crates/forge_main/src/lib.rs
- crates/forge_main/src/select.rs
- crates/forge_main/src/ui.rs
- crates/forge_main/src/update.rs
Fixes #1126
Consolidate scattered inquire select operations into a single centralized module with consistent error handling and UX.
- Created `forge_main::select` module with builder pattern API
- Centralized error handling: cancellations → `Ok(None)`
- Unified render configuration with consistent icons (⇡, ⇣, ➤)
- Migrated all usage from `ui.rs` and `update.rs`
```rust
// Simple selection
ForgeSelect::select("Choose option", options).prompt()?
// Confirmation with default
ForgeSelect::confirm("Are you sure?").with_default(true).prompt()?
// Advanced configuration
ForgeSelect::select("Select model", models)
.with_starting_cursor(index)
.with_help_message("Custom help")
.prompt()?
```
> refactor: consolidate inquire select functionality into select module

- crates/forge_app/src/fmt/fmt_input.rs
- crates/forge_app/src/fmt/fmt_output.rs
- crates/forge_app/src/operation.rs
- crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_max_output.snap
- crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_output.snap
- crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_with_results.snap
- crates/forge_app/src/truncation.rs
- crates/forge_app/src/utils.rs
- Fixed issue #1138 where search results relative paths were using current working directory (CWD) instead of the search directory
- Search results now correctly show paths relative to the search directory rather than the working directory
- Refactored path formatting utilities to support custom base directories
- **Modified `utils.rs`**: Replaced `display_path` with `format_display_path` and updated `format_match` to accept a base directory parameter
- **Updated `truncation.rs`**: Modified `truncate_search_output` to use search directory for relative path calculations
- **Fixed `operation.rs`**: Updated search operation to pass search directory to truncation function
- **Updated test snapshots**: Accepted new correct behavior in test snapshots
fixed #1138
> fix: use search directory for relative paths in search results instead of CWD

- crates/forge_services/src/tool_services/fs_search.rs
> fix: skip binary files while searching

- crates/forge_app/src/orch.rs
- crates/forge_domain/src/context.rs
The signature generated for extended thinking is not required at all for summarization. It only consumes input tokens and doesn't contribute to the final result, so it can be dropped.
> fix: signature is not required for summarization

- crates/forge_domain/src/conversation.rs
- crates/forge_main/src/ui.rs
> fix: prevent overwriting existing agent models

- README.md
- crates/forge_main/src/ui.rs
- zsh-plugin/forge.plugin.zsh
- **feat: add ZSH plugin configuration section to README.md**
- **fix: prompt for new conversation only in interactive mode**
> fix: hide "new task" prompt if running in non-interactive mode

- crates/forge_main/src/info.rs
- crates/forge_main/src/ui.rs
- shell-plugin/forge.plugin.zsh
- Showing conversation information before and after the conversation
- Typing `@` in ZSH will auto-trigger the file selector
- Changed the pattern from `#?` to `??`
- Improved colors for text after the `??` sentinel
- CTRL + K will clear the conversation (TEMP FIX)
> fix: minor ZSH plugin improvements

- shell-plugin/forge.plugin.zsh
- **fix: add log message for resetting operating agent in forge-accept-line function**
- **fix: handle empty user-input**
> fix(zsh): empty prompts will set the agent

- crates/forge_main/src/banner.rs
- crates/forge_main/src/model.rs
fixes https://github.com/antinomyhq/forge/issues/1649
> fix: correct command references from "/conversations" to "/conversation"

- crates/forge_infra/src/database/repository/conversation.rs
- **refactor: replace 'inquire' with 'dialoguer' for improved user prompts**
- **refactor: replace 'inquire' with 'dialoguer' in dependencies**
- **refactor: streamline command execution and prompt reset functions**
- **fix: sort conversations by updated at**
> fix: order of conversation by `updated_at`

- shell-plugin/forge.plugin.zsh
By mistake committed my local setting in one of the PR reverting it to use forge
> fix: revert `FORGE_BIN` to default 'forge' for consistency
